-- auto-generated definition
create table video_entity
(
    video_id          bigint generated by default as identity
        primary key,
    author_username   varchar(255) not null,
    description       varchar(255),
    hash              varchar(255) not null,
    name              varchar(255) not null,
    resolution_height varchar(255) not null
);

