apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: C:/Youtube/Videos