drop table if exists user_entity CASCADE;

create table user_entity (
    user_id bigint generated by default as identity,
    email varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (user_id)
);

alter table user_entity
    add constraint user_email_unique
        unique (email);

alter table user_entity
    add constraint user_username_unique
        unique (username);