apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-converter.fullname" . }}
  labels:
    {{- include "video-converter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9002
      name: http
  selector:
    {{- include "video-converter.selectorLabels" . | nindent 4 }}
